package github.kyrenesjtv.albertadmin.entity.po;

import java.util.Date;

public class GlobalSetup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_setup.id
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_setup.logo
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String logo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_setup.organization
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String organization;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_setup.systemName
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String systemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_setup.version
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_setup.createDate
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_setup.createId
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_setup.createName
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String createName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_setup.copyRight
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String copyRight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_setup.support
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String support;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_setup.id
     *
     * @return the value of global_setup.id
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_setup.id
     *
     * @param id the value for global_setup.id
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_setup.logo
     *
     * @return the value of global_setup.logo
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_setup.logo
     *
     * @param logo the value for global_setup.logo
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setLogo(String logo) {
        this.logo = logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_setup.organization
     *
     * @return the value of global_setup.organization
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getOrganization() {
        return organization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_setup.organization
     *
     * @param organization the value for global_setup.organization
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setOrganization(String organization) {
        this.organization = organization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_setup.systemName
     *
     * @return the value of global_setup.systemName
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getSystemName() {
        return systemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_setup.systemName
     *
     * @param systemName the value for global_setup.systemName
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setSystemName(String systemName) {
        this.systemName = systemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_setup.version
     *
     * @return the value of global_setup.version
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_setup.version
     *
     * @param version the value for global_setup.version
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_setup.createDate
     *
     * @return the value of global_setup.createDate
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_setup.createDate
     *
     * @param createDate the value for global_setup.createDate
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_setup.createId
     *
     * @return the value of global_setup.createId
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_setup.createId
     *
     * @param createId the value for global_setup.createId
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setCreateId(String createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_setup.createName
     *
     * @return the value of global_setup.createName
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_setup.createName
     *
     * @param createName the value for global_setup.createName
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setCreateName(String createName) {
        this.createName = createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_setup.copyRight
     *
     * @return the value of global_setup.copyRight
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getCopyRight() {
        return copyRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_setup.copyRight
     *
     * @param copyRight the value for global_setup.copyRight
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setCopyRight(String copyRight) {
        this.copyRight = copyRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_setup.support
     *
     * @return the value of global_setup.support
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getSupport() {
        return support;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_setup.support
     *
     * @param support the value for global_setup.support
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setSupport(String support) {
        this.support = support;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_setup
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", logo=").append(logo);
        sb.append(", organization=").append(organization);
        sb.append(", systemName=").append(systemName);
        sb.append(", version=").append(version);
        sb.append(", createDate=").append(createDate);
        sb.append(", createId=").append(createId);
        sb.append(", createName=").append(createName);
        sb.append(", copyRight=").append(copyRight);
        sb.append(", support=").append(support);
        sb.append("]");
        return sb.toString();
    }
}