package github.kyrenesjtv.albertadmin.entity.po;

import java.util.Date;

public class GlobalDepart {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_depart.id
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_depart.address
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_depart.createDate
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_depart.createUID
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String createUID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_depart.createName
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String createName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_depart.managerUID
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String managerUID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_depart.managerName
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String managerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_depart.name
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_depart.remarks
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_depart.parentId
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_depart.shortName
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String shortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_depart.sort
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private Long sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_depart.state
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private Long state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_depart.telephone
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_depart.zipCode
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String zipCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_depart.orgName
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_depart.orgType
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private Long orgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_depart.orgCode
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_depart.orgLevel
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String orgLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_depart.administrationCode
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String administrationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_depart.administrationLevel
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private Long administrationLevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_depart.id
     *
     * @return the value of global_depart.id
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_depart.id
     *
     * @param id the value for global_depart.id
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_depart.address
     *
     * @return the value of global_depart.address
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_depart.address
     *
     * @param address the value for global_depart.address
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_depart.createDate
     *
     * @return the value of global_depart.createDate
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_depart.createDate
     *
     * @param createDate the value for global_depart.createDate
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_depart.createUID
     *
     * @return the value of global_depart.createUID
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getCreateUID() {
        return createUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_depart.createUID
     *
     * @param createUID the value for global_depart.createUID
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setCreateUID(String createUID) {
        this.createUID = createUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_depart.createName
     *
     * @return the value of global_depart.createName
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_depart.createName
     *
     * @param createName the value for global_depart.createName
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setCreateName(String createName) {
        this.createName = createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_depart.managerUID
     *
     * @return the value of global_depart.managerUID
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getManagerUID() {
        return managerUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_depart.managerUID
     *
     * @param managerUID the value for global_depart.managerUID
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setManagerUID(String managerUID) {
        this.managerUID = managerUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_depart.managerName
     *
     * @return the value of global_depart.managerName
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_depart.managerName
     *
     * @param managerName the value for global_depart.managerName
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setManagerName(String managerName) {
        this.managerName = managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_depart.name
     *
     * @return the value of global_depart.name
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_depart.name
     *
     * @param name the value for global_depart.name
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_depart.remarks
     *
     * @return the value of global_depart.remarks
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_depart.remarks
     *
     * @param remarks the value for global_depart.remarks
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_depart.parentId
     *
     * @return the value of global_depart.parentId
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_depart.parentId
     *
     * @param parentId the value for global_depart.parentId
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_depart.shortName
     *
     * @return the value of global_depart.shortName
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_depart.shortName
     *
     * @param shortName the value for global_depart.shortName
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_depart.sort
     *
     * @return the value of global_depart.sort
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public Long getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_depart.sort
     *
     * @param sort the value for global_depart.sort
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setSort(Long sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_depart.state
     *
     * @return the value of global_depart.state
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public Long getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_depart.state
     *
     * @param state the value for global_depart.state
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setState(Long state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_depart.telephone
     *
     * @return the value of global_depart.telephone
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_depart.telephone
     *
     * @param telephone the value for global_depart.telephone
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_depart.zipCode
     *
     * @return the value of global_depart.zipCode
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_depart.zipCode
     *
     * @param zipCode the value for global_depart.zipCode
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_depart.orgName
     *
     * @return the value of global_depart.orgName
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_depart.orgName
     *
     * @param orgName the value for global_depart.orgName
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_depart.orgType
     *
     * @return the value of global_depart.orgType
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public Long getOrgType() {
        return orgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_depart.orgType
     *
     * @param orgType the value for global_depart.orgType
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setOrgType(Long orgType) {
        this.orgType = orgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_depart.orgCode
     *
     * @return the value of global_depart.orgCode
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_depart.orgCode
     *
     * @param orgCode the value for global_depart.orgCode
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_depart.orgLevel
     *
     * @return the value of global_depart.orgLevel
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getOrgLevel() {
        return orgLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_depart.orgLevel
     *
     * @param orgLevel the value for global_depart.orgLevel
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setOrgLevel(String orgLevel) {
        this.orgLevel = orgLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_depart.administrationCode
     *
     * @return the value of global_depart.administrationCode
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getAdministrationCode() {
        return administrationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_depart.administrationCode
     *
     * @param administrationCode the value for global_depart.administrationCode
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setAdministrationCode(String administrationCode) {
        this.administrationCode = administrationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_depart.administrationLevel
     *
     * @return the value of global_depart.administrationLevel
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public Long getAdministrationLevel() {
        return administrationLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_depart.administrationLevel
     *
     * @param administrationLevel the value for global_depart.administrationLevel
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setAdministrationLevel(Long administrationLevel) {
        this.administrationLevel = administrationLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_depart
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", address=").append(address);
        sb.append(", createDate=").append(createDate);
        sb.append(", createUID=").append(createUID);
        sb.append(", createName=").append(createName);
        sb.append(", managerUID=").append(managerUID);
        sb.append(", managerName=").append(managerName);
        sb.append(", name=").append(name);
        sb.append(", remarks=").append(remarks);
        sb.append(", parentId=").append(parentId);
        sb.append(", shortName=").append(shortName);
        sb.append(", sort=").append(sort);
        sb.append(", state=").append(state);
        sb.append(", telephone=").append(telephone);
        sb.append(", zipCode=").append(zipCode);
        sb.append(", orgName=").append(orgName);
        sb.append(", orgType=").append(orgType);
        sb.append(", orgCode=").append(orgCode);
        sb.append(", orgLevel=").append(orgLevel);
        sb.append(", administrationCode=").append(administrationCode);
        sb.append(", administrationLevel=").append(administrationLevel);
        sb.append("]");
        return sb.toString();
    }
}