package github.kyrenesjtv.albertadmin.entity.po;

public class GlobalRoleuser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_roleuser.id
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_roleuser.roleId
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_roleuser.userId
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_roleuser.id
     *
     * @return the value of global_roleuser.id
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_roleuser.id
     *
     * @param id the value for global_roleuser.id
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_roleuser.roleId
     *
     * @return the value of global_roleuser.roleId
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_roleuser.roleId
     *
     * @param roleId the value for global_roleuser.roleId
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_roleuser.userId
     *
     * @return the value of global_roleuser.userId
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_roleuser.userId
     *
     * @param userId the value for global_roleuser.userId
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_roleuser
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roleId=").append(roleId);
        sb.append(", userId=").append(userId);
        sb.append("]");
        return sb.toString();
    }
}