package github.kyrenesjtv.albertadmin.entity.po;

import java.util.Date;

public class GlobalFunction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_function.id
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_function.createDate
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_function.createUId
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String createUId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_function.createName
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String createName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_function.address
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_function.icon
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_function.name
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_function.remarks
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_function.parentId
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_function.sort
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private Long sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_function.state
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private Long state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_function.type
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private Long type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_function.visibility
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String visibility;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_function.id
     *
     * @return the value of global_function.id
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_function.id
     *
     * @param id the value for global_function.id
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_function.createDate
     *
     * @return the value of global_function.createDate
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_function.createDate
     *
     * @param createDate the value for global_function.createDate
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_function.createUId
     *
     * @return the value of global_function.createUId
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getCreateUId() {
        return createUId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_function.createUId
     *
     * @param createUId the value for global_function.createUId
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setCreateUId(String createUId) {
        this.createUId = createUId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_function.createName
     *
     * @return the value of global_function.createName
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_function.createName
     *
     * @param createName the value for global_function.createName
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setCreateName(String createName) {
        this.createName = createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_function.address
     *
     * @return the value of global_function.address
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_function.address
     *
     * @param address the value for global_function.address
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_function.icon
     *
     * @return the value of global_function.icon
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_function.icon
     *
     * @param icon the value for global_function.icon
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_function.name
     *
     * @return the value of global_function.name
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_function.name
     *
     * @param name the value for global_function.name
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_function.remarks
     *
     * @return the value of global_function.remarks
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_function.remarks
     *
     * @param remarks the value for global_function.remarks
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_function.parentId
     *
     * @return the value of global_function.parentId
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_function.parentId
     *
     * @param parentId the value for global_function.parentId
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_function.sort
     *
     * @return the value of global_function.sort
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public Long getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_function.sort
     *
     * @param sort the value for global_function.sort
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setSort(Long sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_function.state
     *
     * @return the value of global_function.state
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public Long getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_function.state
     *
     * @param state the value for global_function.state
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setState(Long state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_function.type
     *
     * @return the value of global_function.type
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public Long getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_function.type
     *
     * @param type the value for global_function.type
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setType(Long type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_function.visibility
     *
     * @return the value of global_function.visibility
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getVisibility() {
        return visibility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_function.visibility
     *
     * @param visibility the value for global_function.visibility
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setVisibility(String visibility) {
        this.visibility = visibility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_function
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", createDate=").append(createDate);
        sb.append(", createUId=").append(createUId);
        sb.append(", createName=").append(createName);
        sb.append(", address=").append(address);
        sb.append(", icon=").append(icon);
        sb.append(", name=").append(name);
        sb.append(", remarks=").append(remarks);
        sb.append(", parentId=").append(parentId);
        sb.append(", sort=").append(sort);
        sb.append(", state=").append(state);
        sb.append(", type=").append(type);
        sb.append(", visibility=").append(visibility);
        sb.append("]");
        return sb.toString();
    }
}