package github.kyrenesjtv.albertadmin.entity.po;

import java.util.Date;

public class GlobalRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_role.id
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_role.createDate
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_role.createId
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_role.createrName
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String createrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_role.name
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_role.remarks
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_role.sort
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private Long sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_role.state
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private Long state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_role.id
     *
     * @return the value of global_role.id
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_role.id
     *
     * @param id the value for global_role.id
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_role.createDate
     *
     * @return the value of global_role.createDate
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_role.createDate
     *
     * @param createDate the value for global_role.createDate
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_role.createId
     *
     * @return the value of global_role.createId
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_role.createId
     *
     * @param createId the value for global_role.createId
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setCreateId(String createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_role.createrName
     *
     * @return the value of global_role.createrName
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getCreaterName() {
        return createrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_role.createrName
     *
     * @param createrName the value for global_role.createrName
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setCreaterName(String createrName) {
        this.createrName = createrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_role.name
     *
     * @return the value of global_role.name
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_role.name
     *
     * @param name the value for global_role.name
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_role.remarks
     *
     * @return the value of global_role.remarks
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_role.remarks
     *
     * @param remarks the value for global_role.remarks
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_role.sort
     *
     * @return the value of global_role.sort
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public Long getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_role.sort
     *
     * @param sort the value for global_role.sort
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setSort(Long sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_role.state
     *
     * @return the value of global_role.state
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public Long getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_role.state
     *
     * @param state the value for global_role.state
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setState(Long state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_role
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", createDate=").append(createDate);
        sb.append(", createId=").append(createId);
        sb.append(", createrName=").append(createrName);
        sb.append(", name=").append(name);
        sb.append(", remarks=").append(remarks);
        sb.append(", sort=").append(sort);
        sb.append(", state=").append(state);
        sb.append("]");
        return sb.toString();
    }
}