package github.kyrenesjtv.albertadmin.entity.po;

public class GlobalRoleFunction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_role_function.id
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_role_function.roleId
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_role_function.functionId
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String functionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_role_function.id
     *
     * @return the value of global_role_function.id
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_role_function.id
     *
     * @param id the value for global_role_function.id
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_role_function.roleId
     *
     * @return the value of global_role_function.roleId
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_role_function.roleId
     *
     * @param roleId the value for global_role_function.roleId
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_role_function.functionId
     *
     * @return the value of global_role_function.functionId
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getFunctionId() {
        return functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_role_function.functionId
     *
     * @param functionId the value for global_role_function.functionId
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setFunctionId(String functionId) {
        this.functionId = functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_role_function
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roleId=").append(roleId);
        sb.append(", functionId=").append(functionId);
        sb.append("]");
        return sb.toString();
    }
}