package github.kyrenesjtv.albertadmin.entity.po;

import java.util.Date;

public class GlobalLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_log.id
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_log.description
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_log.functionId
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String functionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_log.ip
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_log.loginName
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_log.operationDate
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private Date operationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_log.operationType
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private Long operationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_log.functionName
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String functionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_log.createId
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_log.createName
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String createName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_log.logType
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private Long logType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_log.operationCate
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String operationCate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_log.describe
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    private String describe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_log.id
     *
     * @return the value of global_log.id
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_log.id
     *
     * @param id the value for global_log.id
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_log.description
     *
     * @return the value of global_log.description
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_log.description
     *
     * @param description the value for global_log.description
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_log.functionId
     *
     * @return the value of global_log.functionId
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getFunctionId() {
        return functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_log.functionId
     *
     * @param functionId the value for global_log.functionId
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setFunctionId(String functionId) {
        this.functionId = functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_log.ip
     *
     * @return the value of global_log.ip
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_log.ip
     *
     * @param ip the value for global_log.ip
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_log.loginName
     *
     * @return the value of global_log.loginName
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_log.loginName
     *
     * @param loginName the value for global_log.loginName
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_log.operationDate
     *
     * @return the value of global_log.operationDate
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public Date getOperationDate() {
        return operationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_log.operationDate
     *
     * @param operationDate the value for global_log.operationDate
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setOperationDate(Date operationDate) {
        this.operationDate = operationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_log.operationType
     *
     * @return the value of global_log.operationType
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public Long getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_log.operationType
     *
     * @param operationType the value for global_log.operationType
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setOperationType(Long operationType) {
        this.operationType = operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_log.functionName
     *
     * @return the value of global_log.functionName
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getFunctionName() {
        return functionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_log.functionName
     *
     * @param functionName the value for global_log.functionName
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setFunctionName(String functionName) {
        this.functionName = functionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_log.createId
     *
     * @return the value of global_log.createId
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_log.createId
     *
     * @param createId the value for global_log.createId
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setCreateId(String createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_log.createName
     *
     * @return the value of global_log.createName
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_log.createName
     *
     * @param createName the value for global_log.createName
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setCreateName(String createName) {
        this.createName = createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_log.logType
     *
     * @return the value of global_log.logType
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public Long getLogType() {
        return logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_log.logType
     *
     * @param logType the value for global_log.logType
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setLogType(Long logType) {
        this.logType = logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_log.operationCate
     *
     * @return the value of global_log.operationCate
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getOperationCate() {
        return operationCate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_log.operationCate
     *
     * @param operationCate the value for global_log.operationCate
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setOperationCate(String operationCate) {
        this.operationCate = operationCate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_log.describe
     *
     * @return the value of global_log.describe
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_log.describe
     *
     * @param describe the value for global_log.describe
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    public void setDescribe(String describe) {
        this.describe = describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_log
     *
     * @mbggenerated Fri Jan 29 13:41:20 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", description=").append(description);
        sb.append(", functionId=").append(functionId);
        sb.append(", ip=").append(ip);
        sb.append(", loginName=").append(loginName);
        sb.append(", operationDate=").append(operationDate);
        sb.append(", operationType=").append(operationType);
        sb.append(", functionName=").append(functionName);
        sb.append(", createId=").append(createId);
        sb.append(", createName=").append(createName);
        sb.append(", logType=").append(logType);
        sb.append(", operationCate=").append(operationCate);
        sb.append(", describe=").append(describe);
        sb.append("]");
        return sb.toString();
    }
}